name: AllBreakTools
main: io.github.maple8192.allbreaktools.AllBreakTools
version: '${version}'
description: 設定したブロックを一括で破壊するプラグインです。
api-version: 1.18
depend: [ KotlinPluginLib ]
authors: [ Maple8192 ]
